### ISSUE TITLE
Add isEnabled methods

### ISSUE THREAD

**Issue by stefan-nsk** [noveogroup/android-logger#29]
+ Log.isVerboseEnabled()
+ Log.isDebugEnabled()
... etc ...

**Comment by devtestr** [comment]
I use your library for logging and I could not disable the logging in props.
Imp classes:
import com.noveogroup.android.log.Logger;
import com.noveogroup.android.log.LoggerManager;
import com.noveogroup.android.log.Log;
Add File \ src \ main \ res \ android-logger.propertis
Props:
root= ASSERT:MyApplication
com.exmpl.myexceptionhandler= ASSERT:MyApplication-Database
com.exmpl.myexceptionhandler=ASSERT:MyApplication-UI
Also tried using this props
root= VERBOSE:MyApplication
com.exmpl.myexceptionhandler= VERBOSE:MyApplication-Database
com.exmpl.myexceptionhandler= VERBOSE:MyApplication-UI
But all From Log.i, Log.e are displayed in both cases and Log.isEnabled(Logger.Level.ERROR) always true.
How can I disable the logs?

**Comment by stefan-nsk** [comment]
Hello,

There are two mistakes:
1. File "android-logger.propertis" should be "android-logger.properti**e**s"
2. Property "com.exmpl.myexceptionhandler" is configured twice, so "MyApplication-UI" replaces "MyApplication-Database".

Hope it helps you.

**Comment by stefan-nsk** [comment]
is&lt;Level&gt;Enabled() methods implemented in 2f4671dd09602a4e0c888364af71ab2eb190df80
