### ISSUE TITLE
tag from classname

### ISSUE THREAD

**Issue by paleozogt** [noveogroup/android-logger#40]
In logback-android, the 'tag' comes from the name of the class passed to ```Logger.getLogger```.  However, in android-logger the 'tag' has to be hard-coded in ```android-logger.properties```.

There should be a way to specify that we want to use the classname as the tag.

**Comment by stefan-nsk** [comment]
Hello,

There is a way to set a pattern for log tag. Try the following `android-logger.properties`:

    root=DEBUG:%logger:[%t] %caller{-5}%source

Here `%logger` is a tag pattern and `[%t] %caller{-5}%source` is a message pattern.
Tag pattern `%logger` means that logger name will be used as a log tag.

You can read more about patterns here: https://github.com/noveogroup/android-logger#patterns
